services:
  web:
    build:
      context: .
    # command: bash -c "python manage.py runserver 0.0.0.0:${WEB_PORT}"
    command: daphne -b 0.0.0.0 -p ${WEB_PORT} core.asgi:application
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  db:
    image: postgres:16.2
    volumes:
      - shop_management_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  redis:
    image: redis:alpine
    ports:
    - "6379:6379"

  worker_default:
    restart: unless-stopped
    build:
      context: .
    command: celery -A core worker --loglevel=info --queues=default --concurrency=2 # 2 workers for default
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

volumes:
  shop_management_db:
  